# Generated by Django 5.1 on 2024-11-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_customuser_organizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='moneda_predeterminada',
            field=models.CharField(choices=[('MXN', 'MXN - Moneda Nacional Mexicana'), ('USD', 'USD - Dolar Estadunidense')], default='MXN', max_length=10, verbose_name='Moneda Predeterminada'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='metodo_pago',
            field=models.CharField(choices=[('MXN', 'MXN - Moneda Nacional Mexicana'), ('USD', 'USD - Dolar Estadunidense')], max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='moneda',
            field=models.CharField(blank=True, choices=[('MXN', 'MXN - Moneda Nacional Mexicana'), ('USD', 'USD - Dolar Estadunidense')], max_length=10, null=True),
        ),
    ]
