# Generated by Django 5.1 on 2024-12-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_configuracionsistema_moneda_predeterminada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contenedor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_matriz', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Preservador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_perservador', models.CharField(max_length=20)),
            ],
        ),
    ]
