# Generated by Django 5.1 on 2024-12-17 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_contenedores_matriz_preservador'),
    ]

    operations = [
        migrations.CreateModel(
            name='claves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_clave', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='info_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=30)),
                ('direccion_cliente', models.CharField(max_length=200)),
                ('contacto_cliente', models.CharField(max_length=30)),
                ('puesto_cargo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='laboratorio_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_laboratorio', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='orden_trabajo_ot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_orden_trabajo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='parametro_analitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcin_analitic', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='sample_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='unidad_medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='cadena_externa',
            fields=[
                ('id_ce', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('datetime_muestreo', models.DateTimeField(auto_now=True)),
                ('horafinal', models.DateTimeField(auto_now=True)),
                ('volumen_cantidad', models.CharField(max_length=30)),
                ('id_filtor', models.CharField(max_length=10)),
                ('origen_muestra', models.CharField(max_length=50)),
                ('id_contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.contenedores')),
                ('id_matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.matriz')),
                ('id_preservador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.preservador')),
                ('id_clave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.claves')),
                ('id_inforclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.info_cliente')),
                ('id_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.laboratorio_id')),
                ('id_ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.orden_trabajo_ot')),
                ('id_parametro_analitico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parametro_analitico')),
                ('id_prioridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.prioridad')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sample_type')),
                ('id_unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.unidad_medida')),
            ],
        ),
        migrations.CreateModel(
            name='cadena_interna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cadena_externa')),
            ],
        ),
    ]
