# Generated by Django 5.1 on 2024-12-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_claves_info_cliente_laboratorio_id_orden_trabajo_ot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadena_interna',
            old_name='id_ce',
            new_name='ce',
        ),
    ]
