# Generated by Django 5.1 on 2024-12-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_rename_id_ce_cadena_interna_ce'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedores',
            name='letra_contenedor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='matriz',
            name='letra_matriz',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='name_matriz',
            field=models.CharField(max_length=10),
        ),
    ]
