# Generated by Django 5.1 on 2024-12-18 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_contenedores_letra_contenedor_matriz_letra_matriz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriz',
            name='name_matriz',
        ),
        migrations.AlterField(
            model_name='cadena_externa',
            name='id_clave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.claves'),
        ),
        migrations.AlterField(
            model_name='cadena_externa',
            name='id_contenedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contenedores'),
        ),
        migrations.AlterField(
            model_name='cadena_externa',
            name='id_inforclient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.info_cliente'),
        ),
        migrations.AlterField(
            model_name='cadena_externa',
            name='id_laboratorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.laboratorio_id'),
        ),
        migrations.AlterField(
            model_name='cadena_externa',
            name='id_matriz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.matriz'),
        ),
        migrations.AlterField(
            model_name='cadena_externa',
            name='id_ot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.orden_trabajo_ot'),
        ),
        migrations.AlterField(
            model_name='cadena_externa',
            name='id_parametro_analitico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.parametro_analitico'),
        ),
        migrations.AlterField(
            model_name='cadena_externa',
            name='id_preservador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.preservador'),
        ),
        migrations.AlterField(
            model_name='cadena_externa',
            name='id_prioridad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.prioridad'),
        ),
        migrations.AlterField(
            model_name='cadena_externa',
            name='id_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.sample_type'),
        ),
        migrations.AlterField(
            model_name='cadena_externa',
            name='id_unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.unidad_medida'),
        ),
        migrations.AlterField(
            model_name='info_cliente',
            name='puesto_cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='related_option',
            fields=[
                ('opcion_relacion', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id_matriz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.matriz')),
                ('id_parametro_analitico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.parametro_analitico')),
                ('id_preservadores', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.preservador')),
            ],
        ),
        migrations.AddField(
            model_name='cadena_externa',
            name='id_opcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.related_option'),
        ),
    ]
