# Generated by Django 5.1 on 2024-12-18 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_option_matriz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option_matriz',
            old_name='id_option_matriz',
            new_name='id_om',
        ),
        migrations.RemoveField(
            model_name='related_option',
            name='id_matriz',
        ),
        migrations.AddField(
            model_name='option_matriz',
            name='g_option',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option_matriz',
            name='l_option',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option_matriz',
            name='o_option',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='related_option',
            name='id_opt_ma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.option_matriz'),
        ),
        migrations.AlterField(
            model_name='option_matriz',
            name='s_option',
            field=models.IntegerField(default=0),
        ),
    ]
