# Generated by Django 5.1 on 2024-12-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_rename_id_option_matriz_option_matriz_id_om_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='related_option',
            old_name='id_opt_ma',
            new_name='option_matriz_f',
        ),
    ]
