# Generated by Django 5.1 on 2024-12-19 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_rename_id_opt_ma_related_option_option_matriz_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadena_externa',
            name='id_laboratorio',
        ),
        migrations.RemoveField(
            model_name='related_option',
            name='option_matriz_f',
        ),
        migrations.RemoveField(
            model_name='cadena_externa',
            name='id_ot',
        ),
        migrations.RemoveField(
            model_name='related_option',
            name='id_parametro_analitico',
        ),
        migrations.RemoveField(
            model_name='related_option',
            name='id_preservadores',
        ),
        migrations.RemoveField(
            model_name='cadena_externa',
            name='id_opcion',
        ),
        migrations.RemoveField(
            model_name='cadena_externa',
            name='datetime_muestreo',
        ),
        migrations.RemoveField(
            model_name='cadena_externa',
            name='horafinal',
        ),
        migrations.RemoveField(
            model_name='cadena_externa',
            name='id_clave',
        ),
        migrations.RemoveField(
            model_name='cadena_externa',
            name='id_contenedor',
        ),
        migrations.RemoveField(
            model_name='cadena_externa',
            name='id_filtor',
        ),
        migrations.RemoveField(
            model_name='cadena_externa',
            name='id_inforclient',
        ),
        migrations.RemoveField(
            model_name='cadena_externa',
            name='id_matriz',
        ),
        migrations.RemoveField(
            model_name='cadena_externa',
            name='id_parametro_analitico',
        ),
        migrations.RemoveField(
            model_name='cadena_externa',
            name='id_preservador',
        ),
        migrations.RemoveField(
            model_name='cadena_externa',
            name='id_prioridad',
        ),
        migrations.RemoveField(
            model_name='cadena_externa',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='cadena_externa',
            name='id_unidad_medida',
        ),
        migrations.RemoveField(
            model_name='cadena_externa',
            name='origen_muestra',
        ),
        migrations.RemoveField(
            model_name='cadena_externa',
            name='volumen_cantidad',
        ),
        migrations.RemoveField(
            model_name='cadena_interna',
            name='ce',
        ),
        migrations.CreateModel(
            name='outer_chain_row',
            fields=[
                ('outer_chain_row', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('id_orden_trabajo', models.CharField(max_length=100)),
                ('id_laboratorio', models.CharField(max_length=100)),
                ('datetime_muestreo', models.DateTimeField(auto_now=True)),
                ('horafinal', models.DateTimeField(auto_now=True)),
                ('volumen_cantidad', models.CharField(max_length=30)),
                ('id_filtor', models.CharField(max_length=10)),
                ('origen_muestra', models.CharField(max_length=50)),
                ('id_ce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.cadena_externa')),
                ('id_clave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.claves')),
                ('id_contenedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contenedores')),
                ('id_inforclient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.info_cliente')),
                ('id_parametro_analitico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.parametro_analitico')),
                ('id_prioridad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.prioridad')),
                ('id_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.sample_type')),
                ('id_unidad_medida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.unidad_medida')),
            ],
        ),
        migrations.CreateModel(
            name='opcion_matriz',
            fields=[
                ('matriz_option', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('outer_chair_row', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.outer_chain_row')),
            ],
        ),
        migrations.CreateModel(
            name='inte_perservador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Preservador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.preservador')),
                ('outer_chain_row', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.outer_chain_row')),
            ],
        ),
        migrations.CreateModel(
            name='inte_parametro_analitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro_analitico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.parametro_analitico')),
                ('id_outer_chair_row', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.outer_chain_row')),
            ],
        ),
        migrations.CreateModel(
            name='inte_matriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.matriz')),
                ('outer_chain_row', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.outer_chain_row')),
            ],
        ),
        migrations.AddField(
            model_name='cadena_interna',
            name='outer_chain_row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.outer_chain_row'),
        ),
        migrations.DeleteModel(
            name='laboratorio_id',
        ),
        migrations.DeleteModel(
            name='option_matriz',
        ),
        migrations.DeleteModel(
            name='orden_trabajo_ot',
        ),
        migrations.DeleteModel(
            name='related_option',
        ),
    ]
