# Generated by Django 5.1 on 2024-12-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_remove_cadena_externa_id_laboratorio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contenedores',
            new_name='Contenedor',
        ),
    ]
