# Generated by Django 5.1 on 2024-12-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_contenedor_letra_contenedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outer_chain_row',
            name='datetime_muestreo',
            field=models.DateTimeField(),
        ),
    ]
