# Generated by Django 5.1 on 2024-12-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_contenedor_letra_contenedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioridad',
            name='day_min',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
