# Generated by Django 5.1 on 2024-12-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_prioridad_day_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outer_chain_row',
            name='volumen_cantidad',
        ),
        migrations.DeleteModel(
            name='opcion_matriz',
        ),
    ]
