# Generated by Django 5.1 on 2024-12-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_remove_outer_chain_row_volumen_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadena_externa',
            old_name='id_ce',
            new_name='ce',
        ),
    ]
