# Generated by Django 5.1 on 2024-12-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_rename_id_ce_cadena_externa_ce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadena_externa',
            name='ce',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
