# Generated by Django 5.1 on 2024-12-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_alter_cadena_externa_ce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inte_perservador',
            old_name='Preservador',
            new_name='preservador',
        ),
    ]
