# Generated by Django 5.1 on 2024-12-20 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_rename_preservador_inte_perservador_preservador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outer_chain_row',
            old_name='id_unidad_medida',
            new_name='iunidad_medida',
        ),
    ]
