# Generated by Django 5.1 on 2024-12-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_alter_outer_chain_row_outer_chain_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outer_chain_row',
            name='outer_chain_row',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
