# Generated by Django 5.1 on 2024-12-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_alter_outer_chain_row_outer_chain_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outer_chain_row',
            name='datetime_muestreo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='outer_chain_row',
            name='horafinal',
            field=models.DateField(auto_now=True),
        ),
    ]
