# Generated by Django 5.1 on 2025-01-02 17:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_alter_outer_chain_row_datetime_muestreo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outer_chain_row',
            name='id_orden_trabajo',
        ),
        migrations.AddField(
            model_name='cadena_externa',
            name='id_inforclient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.info_cliente'),
        ),
        migrations.AddField(
            model_name='cadena_externa',
            name='id_orden_trabajo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outer_chain_row',
            name='datetime_muestreo',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='outer_chain_row',
            name='horafinal',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
