# Generated by Django 5.1 on 2025-01-02 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_remove_outer_chain_row_id_orden_trabajo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outer_chain_row',
            old_name='id_ce',
            new_name='ce',
        ),
    ]
