# Generated by Django 5.1 on 2025-01-02 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_rename_id_ce_outer_chain_row_ce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outer_chain_row',
            name='id_inforclient',
        ),
        migrations.RemoveField(
            model_name='outer_chain_row',
            name='id_parametro_analitico',
        ),
    ]
