# Generated by Django 5.1 on 2025-01-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_rename_outer_chain_row_outer_chain_row_externa_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inte_matriz',
            old_name='outer_chain_row',
            new_name='externa_row',
        ),
        migrations.RenameField(
            model_name='inte_parametro_analitico',
            old_name='id_outer_chair_row',
            new_name='externa_row',
        ),
        migrations.RenameField(
            model_name='inte_perservador',
            old_name='outer_chain_row',
            new_name='externa_row',
        ),
    ]
