# Generated by Django 5.1 on 2025-01-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_rename_outer_chain_row_inte_matriz_externa_row_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outer_chain_row',
            name='complet',
            field=models.BooleanField(default=0),
        ),
    ]
