# Generated by Django 5.1 on 2025-01-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_outer_chain_row_complet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outer_chain_row',
            name='horafinal',
            field=models.TimeField(null=True),
        ),
    ]
